# Generated by Django 2.2.4 on 2019-08-13 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_application_azure_keys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='azure_keys',
            new_name='azure_key',
        ),
    ]
