# Generated by Django 2.2.4 on 2019-08-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190813_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_approved',
            field=models.IntegerField(default=0),
        ),
    ]
