# Generated by Django 2.2.4 on 2019-08-16 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_application_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='is_approved',
        ),
    ]
