# Generated by Django 2.2.4 on 2019-08-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190816_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='contract_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
