# Generated by Django 2.2.4 on 2019-08-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_application_contract_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='contract_id',
            field=models.TextField(),
        ),
    ]
